const RULES_VERSION = "network-1";
const TOKEN_KEY = "big-hero.session-token";
const ACCOUNT_KEY = "big-hero.account";
const $ = (id) => document.getElementById(id);
const state = { token: sessionStorage.getItem(TOKEN_KEY), account: readJson(ACCOUNT_KEY), character: null, game: null, socket: null, heartbeat: null, reconnectTimer: null, reconnectStartedAt: 0, autoTimer: null, messages: [], registerMode: false, battle: null, battleTimer: null, battleSpeed: 1 };
const ITEM_NAMES = { 1: "回复药水", 2: "大回复药", 3: "经验卷轴", 4: "金币袋", 5: "天命卡", 6: "打孔器", 90: "铁矿石", 91: "龙鳞片" };
const ITEM_ICONS = { 1: "🧪", 2: "🧴", 3: "📜", 4: "💰", 5: "🃏", 6: "🛠", 90: "⛰", 91: "🪶" };
const SKILLS = [[1,"重击", "⚔",0],[2,"猛力一击","💥",1000],[3,"蓄力斩","⚡",10000],[4,"碎裂打击","🪨",10000],[5,"致命一击","🗡",100000],[6,"终结技","🎯",100000],[7,"快速打击","⚡",1000],[8,"连击","💥",1000],[9,"旋风斩","🌀",10000],[10,"连射","🏹",10000],[11,"回旋镖","🪃",10000],[12,"无尽打击","♾",50000],[13,"冰冻射击","❄",10000],[14,"冰霜新星","🧊",50000],[15,"眩晕锤","🔨",10000],[16,"雷霆一击","⚡",10000],[17,"静默领域","🔇",50000],[18,"深度冻结","❄️",100000],[19,"腐蚀之触","💀",50000],[20,"时间凝滞","⏳",100000],[21,"护盾","🛡",1000],[22,"治疗波","💚",0],[23,"铁壁姿态","🏰",10000],[24,"坚毅","💪",50000],[25,"生命绽放","🌿",50000],[26,"不屈意志","❤️‍🔥",100000],[27,"毒刃","🗡",1000],[28,"烈焰灼烧","🔥",10000],[29,"撕裂","🩸",10000],[30,"毒雾","☁️",50000],[31,"剧毒爆发","💚",50000],[32,"瘟疫传播","🦠",100000],[33,"穿刺射击","🏹",1000],[34,"裂地斩","🌍",50000],[35,"穿透箭雨","🌧",10000],[36,"暗影突袭","🌑",100000]];
const GRID_ICONS = ["🏠","⚔️","🗡️","🏆","🛌","🎁","🔨","🎲","🏛","🔮","⚡","💀","🟩","💰","🎰"];
const SLOT_NAMES = { weapon:"武器", armor:"防具", shoes:"鞋子", ring:"戒指", necklace:"项链", cape:"披风", helmet:"头盔", charm:"护符" };
const QUALITY_NAMES = ["普通","精良","稀有","史诗","传说"];
const QUALITY_COLORS = ["#8994a5","#38a874","#3f83cf","#985bd1","#d28a24"];
const SLOT_FOLDER = { weapon:"weapon", armor:"armor", shoes:"shoes", ring:"ring", necklace:"charm", cape:"armor", helmet:"helmet", charm:"charm" };
const $all = (selector, root = document) => [...root.querySelectorAll(selector)];
function readJson(key) { try { return JSON.parse(sessionStorage.getItem(key) || "null"); } catch { return null; } }
function requestId(prefix) { return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}${Math.random().toString(36).slice(2)}`.slice(0, 64); }
function setError(id, message = "") { const node = $(id); if (node) node.textContent = message; }
function errorText(error) { return error?.message || "网络暂时不可用，请稍后重试"; }
function show(id) { const node = $(id); if (node) node.hidden = false; }
function hide(id) { const node = $(id); if (node) node.hidden = true; }
async function api(path, options = {}) { const headers = { "content-type": "application/json", ...(options.headers || {}) }; if (state.token) headers.authorization = `Bearer ${state.token}`; const response = await fetch(path, { ...options, headers }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.ok === false) throw Object.assign(new Error(payload.error?.message || "请求失败"), { code: payload.error?.code, status: response.status }); return payload; }
async function gameCommand(path, command, payload = {}) { const result = await api(path, { method: "POST", body: JSON.stringify({ rules_version: RULES_VERSION, request_id: requestId(command), payload }) }); updateGame(result); return result; }
function setAuthMode(register) { state.registerMode = register; $("auth-title").textContent = register ? "申请账号" : "勇者归来"; $("auth-subtitle").textContent = register ? "使用管理员发放的邀请码创建账号。" : "登录账号，继续朱樱山道的旅程。"; $("auth-submit").textContent = register ? "创建账号" : "进入游戏"; $("auth-switch").textContent = register ? "返回登录" : "使用邀请码注册账号"; $("register-fields").hidden = !register; $("password-confirm").required = register; $("invite-code").required = register; setError("auth-error"); }
function updatePlayer() { const c = state.character; if (!c) return; $("player-name").textContent = c.name; $("map-player-name").textContent = c.name; $("battle-player-name").textContent = c.name; $("hero-level").textContent = `Lv.${c.level}`; $("player-meta").textContent = `Lv.${c.level} · ${c.experience} EXP · ${c.gold} 金币`; $("gold-value").textContent = Number(c.gold).toLocaleString(); }
function showLoggedIn() { hide("auth-view"); hide("character-view"); show("game-view"); updatePlayer(); connectSocket(); refreshOnlineCount(); loadGameState(); }
function showCharacterCreation() { hide("auth-view"); hide("game-view"); show("character-view"); $("character-name").focus(); }
function showLogin() { hide("game-view"); hide("character-view"); show("auth-view"); $("username").focus(); }
async function login() { const result = await api("/api/v1/auth/login", { method:"POST", body:JSON.stringify({ rules_version:RULES_VERSION, username:$("username").value, password:$("password").value }) }); state.token=result.session.token; state.account=result.account; state.character=result.character; sessionStorage.setItem(TOKEN_KEY,state.token); sessionStorage.setItem(ACCOUNT_KEY,JSON.stringify(state.account)); $("password").value=""; if (state.character) showLoggedIn(); else showCharacterCreation(); }
async function register() { const payload={ rules_version:RULES_VERSION, request_id:requestId("register"), username:$("username").value, password:$("password").value, password_confirm:$("password-confirm").value, invite_code:$("invite-code").value }; await api("/api/v1/auth/register",{method:"POST",body:JSON.stringify(payload)}); setAuthMode(false); $("username").value=payload.username; $("password").value=""; setError("auth-error","账号创建成功，请登录。"); }
async function createCharacter(event) { event.preventDefault(); setError("character-error"); try { const result=await api("/api/v1/characters",{method:"POST",body:JSON.stringify({rules_version:RULES_VERSION,request_id:requestId("character"),name:$("character-name").value})}); state.character=result.character; showLoggedIn(); } catch(error) { setError("character-error",errorText(error)); } }
function setConnection(online,label=online?"已连接":"连接中") { $("connection-dot").classList.toggle("online",online); $("connection-label").textContent=label; }
function connectSocket() { if(!state.token || state.socket?.readyState===WebSocket.OPEN || state.socket?.readyState===WebSocket.CONNECTING) return; const protocol=location.protocol==="https:"?"wss:":"ws:"; const socket=new WebSocket(`${protocol}//${location.host}/ws`); state.socket=socket; setConnection(false,"连接中"); socket.addEventListener("open",()=>{state.reconnectStartedAt=0;setConnection(true);socket.send(JSON.stringify({type:"authenticate",token:state.token}));state.heartbeat=window.setInterval(()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:"heartbeat"}));},10000);}); socket.addEventListener("message",event=>{try{handleSocketMessage(JSON.parse(event.data));}catch{}}); socket.addEventListener("close",event=>{window.clearInterval(state.heartbeat);state.heartbeat=null;state.socket=null;if(event.code===4001||event.code===4003){clearSession();return;}setConnection(false,"重连中");scheduleReconnect();}); socket.addEventListener("error",()=>setConnection(false,"连接异常")); }
function scheduleReconnect() { if(state.reconnectTimer||!state.token)return;if(!state.reconnectStartedAt)state.reconnectStartedAt=Date.now();if(Date.now()-state.reconnectStartedAt>30000){clearSession();return;}state.reconnectTimer=window.setTimeout(()=>{state.reconnectTimer=null;connectSocket();},2000); }
function handleSocketMessage(packet) { if(packet.type==="authenticated"){setConnection(true);return;}if(packet.type==="chat_history"){state.messages=Array.isArray(packet.messages)?packet.messages:[];renderMessages();return;}if(packet.type==="chat_message"&&packet.message){if(!state.messages.some(item=>item.id===packet.message.id))state.messages.push(packet.message);state.messages=state.messages.slice(-100);renderMessages();return;}if(packet.type==="error"){if(["SESSION_INVALID","KICKED","REPLACED_BY_NEW_LOGIN"].includes(packet.code))clearSession();else setError("chat-error",packet.message);} }
function renderMessages() { const container=$("chat-messages");if(!container)return;container.replaceChildren();for(const message of state.messages){const item=document.createElement("article");item.className="chat-message";item.innerHTML=`<header><strong></strong><time></time></header><p></p>`;item.querySelector("strong").textContent=message.senderName||"系统";item.querySelector("time").textContent=new Date(message.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});item.querySelector("p").textContent=message.body;container.append(item);}container.scrollTop=container.scrollHeight;$("chat-count").textContent=String(state.messages.length); }
function sendChat(event) { event.preventDefault();const input=$("chat-input"),body=input.value.trim();if(!body||state.socket?.readyState!==WebSocket.OPEN)return;setError("chat-error");state.socket.send(JSON.stringify({type:"chat_send",body,client_message_id:requestId("chat")}));input.value=""; }
async function refreshOnlineCount() { try { const result=await fetch("/healthz");const data=await result.json();$("online-count").textContent=data.online_players??"-"; } catch { $("online-count").textContent="-"; } }
async function loadGameState() { try { const result=await api("/api/v1/game/state");updateGame(result); } catch(error) { setError("game-event",errorText(error)); } }
function updateGame(result) { if(result.character){state.character=result.character;updatePlayer();}if(result.state)state.game=result.state;if(result.event){const event=result.event;const summary=event.message||(event.won===true?"战斗胜利，获得奖励":event.won===false?"战斗失败，消耗了一枚复活币":"行动完成");$("game-event").textContent=`${event.gridName?`${event.icon||""} ${event.gridName}：`:""}${summary}`;if(event.kind==="battle"&&Array.isArray(event.events))playBattle(event); }renderGame(); }
function renderGame() { const game=state.game;if(!game)return;const c=state.character||{};const hp=Math.max(0,game.hp),maxHp=Math.max(1,game.maxHp);$("hp-value").textContent=`${hp} / ${maxHp}`;$("hp-bar").style.width=`${Math.min(100,hp/maxHp*100)}%`;$("exp-value").textContent=`${c.experience||0} / ${(c.level||1)*100}`;$("exp-bar").style.width=`${Math.min(100,(c.experience||0)/Math.max(1,(c.level||1)*100)*100)}%`;$("revive-value").textContent=`${game.reviveCoins} / 3`;$("grid-value").textContent=String((game.gridIndex??0)+1);$("round-value").textContent=String((game.completedLaps||0)+1);$("lap-value").textContent=String(game.completedLaps||0);$("dice-value").textContent=game.lastDiceRoll?String(game.lastDiceRoll):"⚄";$("dice-suit").textContent=["♠","♥","♣","♦"][game.lastDiceSuit??1]||"♥";renderDiceHistory(game);renderMap(game);renderInventory(game);renderSkills(game);renderStats(game);renderAuctionChoices(); }
function renderDiceHistory(game) { const root=$("dice-history");root.replaceChildren();for(const value of (game.diceHistory||[]).slice(-3)){const card=document.createElement("div");card.className="card";card.innerHTML=`<strong>${value}</strong><span>${["♠","♥","♣","♦"][Math.floor(Math.random()*4)]}</span>`;root.append(card);}$("poker-result").textContent=(game.diceHistory||[]).length>=3?"一对 ×2":""; }
function renderMap(game) { const root=$("nearby-cells");root.replaceChildren();const total=game.mapTotalGrids||28;for(let i=0;i<total;i++){const cell=document.createElement("div");cell.className=`route-cell${i===game.gridIndex?" current":""}`;const angle=-Math.PI/2+i/total*Math.PI*2;cell.style.left=`${50+Math.cos(angle)*42}%`;cell.style.top=`${55+Math.sin(angle)*32}%`;cell.innerHTML=`<span>${GRID_ICONS[game.mapGrids[i]]||"·"}</span><small>${i+1}</small>`;root.append(cell);} }
function equipmentIcon(item) { const folder=SLOT_FOLDER[item.slot]||"armor";return `./assets/equipment/${folder}/default.png`; }
function renderInventory(game) { $("equipment-capacity").textContent=`${game.equipmentBag.length} / ${game.equipmentCapacity}`;const eqRoot=$("equipment-list");eqRoot.replaceChildren();for(const item of game.equipmentBag){const equipped=game.equipped[item.slot]===item.id;const enhance=game.slotEnhance[item.slot]||0;const tile=document.createElement("button");tile.className=`equip-tile q${item.quality}${equipped?" worn":""}`;tile.dataset.equipment=item.id;tile.innerHTML=`<img src="${equipmentIcon(item)}" alt=""><b>${item.name}${enhance?` +${enhance}`:""}</b><small>${item.mainStat} +${Math.round(item.mainValue*(1+enhance*.03))}</small><i>${equipped?"已穿戴":""}</i>`;eqRoot.append(tile);}const itemRoot=$("inventory-list");itemRoot.replaceChildren();for(const stack of game.inventory){const row=document.createElement("div");row.className="item-tile";row.innerHTML=`<span>${ITEM_ICONS[stack.itemId]||"◈"}</span><b>${ITEM_NAMES[stack.itemId]||`物品${stack.itemId}`}</b><small>×${stack.count}</small><button data-use-item="${stack.itemId}" type="button">使用</button>`;itemRoot.append(row);}const gemRoot=$("gem-list");gemRoot.replaceChildren();for(const gem of game.gemBag){const row=document.createElement("div");row.className="item-tile";row.innerHTML=`<span>◇</span><b>宝石 #${gem.gemId}</b><small>×${gem.count}</small>`;gemRoot.append(row);}const doll=$all("[data-slot]");for(const slotButton of doll){const slot=slotButton.dataset.slot;const id=game.equipped[slot];const item=game.equipmentBag.find(entry=>entry.id===id);slotButton.classList.toggle("filled",Boolean(item));slotButton.innerHTML=item?`<img src="${equipmentIcon(item)}" alt=""><b>${item.name}</b><small>${SLOT_NAMES[slot]}</small>`:`<span>＋</span><small>${SLOT_NAMES[slot]}</small>`;} }
function renderSkills(game) { const level=state.character?.level||1;const maxSlots=level>=45?6:level>=35?5:level>=15?4:level>=5?3:2;$("skill-slots").textContent=`技能槽 ${game.skillSlots.length} / ${maxSlots}`;const equipped=$("equipped-skills");equipped.replaceChildren();for(const id of game.skillSlots){const s=SKILLS.find(x=>x[0]===id);if(!s)continue;const node=document.createElement("button");node.className="equipped-skill";node.dataset.skill=s[0];node.innerHTML=`<span>${s[2]}</span><b>${s[1]}</b>`;equipped.append(node);}const list=$("skill-list");list.replaceChildren();for(const [id,name,icon,price] of SKILLS){const unlocked=game.skills.includes(id),slotted=game.skillSlots.includes(id);const row=document.createElement("article");row.className=`skill-card${unlocked?" unlocked":" locked"}`;row.innerHTML=`<span class="skill-glyph">${icon}</span><div><strong>${name}</strong><small>${unlocked?(slotted?"已装配 · 点击移出":"已解锁 · 可装配"): `解锁需要 ${price.toLocaleString()} 金币`}</small></div><button data-skill="${id}" data-unlocked="${unlocked}" type="button">${unlocked?(slotted?"移出":"装备"):"解锁"}</button>`;list.append(row);} }
function renderStats(game) { const list=$("stats-list");list.replaceChildren();const stats=[["❤️","生命值",`${game.hp} / ${game.maxHp}`],["⚔","攻击力",game.stats.attack],["🛡","防御力",game.stats.defense],["✦","速度",game.stats.speed],["◎","暴击率",`${game.stats.crit}%`],["✧","技能伤害",`${game.stats.skillDamage}%`],["◇","背包",`${game.inventory.length} / ${game.inventoryCapacity}`],["⚒","装备",`${game.equipmentBag.length} / ${game.equipmentCapacity}`]];for(const [icon,name,value] of stats){const row=document.createElement("div");row.innerHTML=`<span>${icon}</span><b>${name}</b><strong>${value}</strong>`;list.append(row);} }
function renderAuctionChoices() { if(!state.game)return;const kind=$("auction-kind").value,select=$("auction-item-id"),selected=select.value;select.replaceChildren();let choices=[];if(kind==="item")choices=state.game.inventory.map(x=>[String(x.itemId),`${ITEM_NAMES[x.itemId]||`物品${x.itemId}`} ×${x.count}`]);else if(kind==="equipment")choices=state.game.equipmentBag.filter(x=>!x.bound&&!x.locked&&!Object.values(state.game.equipped).includes(x.id)).map(x=>[x.id,x.name]);else choices=state.game.gemBag.filter(x=>x.count>0).map(x=>[String(x.gemId),`宝石 #${x.gemId} ×${x.count}`]);if(!choices.length)choices=[["","没有可上架物品"]];for(const [value,label] of choices){const option=document.createElement("option");option.value=value;option.textContent=label;select.append(option);}if([...select.options].some(x=>x.value===selected))select.value=selected;$("auction-count").disabled=kind==="equipment";if(kind==="equipment")$("auction-count").value="1"; }
function renderAuction(listings=[]) { const list=$("auction-list");list.replaceChildren();if(!listings.length){list.innerHTML="<p class='empty-copy'>当前没有可购买订单。</p>";return;}for(const listing of listings){const itemLabel=listing.itemKind==="equipment"?(listing.item.name||"装备"):listing.itemKind==="gem"?`宝石 #${listing.item.gemId}`:`${ITEM_NAMES[listing.item.itemId]||`物品${listing.item.itemId}`}`;const row=document.createElement("div");row.className="market-row";row.innerHTML=`<div><strong>${itemLabel} ×${listing.itemCount}</strong><small>卖家 ${listing.sellerName} · ${new Date(listing.expiresAt).toLocaleString()}</small></div><b>${listing.buyoutPrice} 金币</b><button class="small-button" data-buy-auction="${listing.id}" type="button">购买</button>`;list.append(row);} }
function renderMyAuction(listings=[]) { const list=$("auction-mine-list");list.replaceChildren();if(!listings.length){list.innerHTML="<p class='empty-copy'>你还没有订单。</p>";return;}for(const listing of listings){const label=listing.itemKind==="equipment"?(listing.item.name||"装备"):listing.itemKind==="gem"?`宝石 #${listing.item.gemId}`:`${ITEM_NAMES[listing.item.itemId]||`物品${listing.item.itemId}`}`;const row=document.createElement("div");row.className="market-row";const canCancel=listing.status==="active",canClaim=["sold","cancelled","expired"].includes(listing.status);row.innerHTML=`<div><strong>${label} ×${listing.itemCount}</strong><small>${listing.status} · ${listing.buyoutPrice} 金币</small></div>${canCancel?`<button class="small-button" data-cancel-auction="${listing.id}" type="button">取消</button>`:""}${canClaim?`<button class="small-button" data-claim-auction="${listing.id}" type="button">领取</button>`:""}`;list.append(row);} }
async function refreshAuction() { try { const result=await api("/api/v1/auction/listings?limit=50");renderAuction(result.listings);const mine=await api("/api/v1/auction/mine");renderMyAuction(mine.listings); } catch(error) { setError("auction-error",errorText(error)); } }
async function roll() { $("roll-button").disabled=true;setError("game-event");try{await gameCommand("/api/v1/game/roll","roll");}catch(error){setError("game-event",errorText(error));}finally{$("roll-button").disabled=false;} }
function setAutoRoll(enabled) { window.clearInterval(state.autoTimer);state.autoTimer=null;if(enabled)state.autoTimer=window.setInterval(()=>{if(!$('roll-button').disabled&&state.token)void roll();},2600); }
async function handleInventoryClick(event) { const use=event.target.closest("[data-use-item]"),tile=event.target.closest("[data-equipment]");try{if(use){await gameCommand("/api/v1/game/item/use","item_use",{item_id:Number(use.dataset.useItem)});return;}if(tile){const item=state.game.equipmentBag.find(x=>x.id===tile.dataset.equipment);if(!item)return;showEquipmentDetail(item);}}catch(error){setError("inventory-error",errorText(error));} }
function showEquipmentDetail(item) { const detail=$("equipment-detail"),equipped=state.game.equipped[item.slot]===item.id,enhance=state.game.slotEnhance[item.slot]||0;detail.innerHTML=`<div class="detail-head"><img src="${equipmentIcon(item)}"><div><h3 style="color:${QUALITY_COLORS[item.quality]}">${item.name}</h3><p>${QUALITY_NAMES[item.quality]} · ${SLOT_NAMES[item.slot]} · ${item.bound?"绑定":"可交易"}</p></div></div><strong>${item.mainStat} +${Math.round(item.mainValue*(1+enhance*.03))}</strong><p>装备槽强化：+${enhance}（每级主属性+3%）</p><div class="detail-actions"><button class="small-button" data-detail-equip="${item.id}" type="button">${equipped?"卸下":"穿戴"}</button><button class="small-button" data-detail-lock="${item.id}" type="button">${item.locked?"解锁":"锁定"}</button><button class="small-button" data-detail-enhance="${item.id}" type="button">强化</button><button class="danger-button" data-detail-dismantle="${item.id}" type="button">分解</button></div>`; }
async function handleDetailAction(event) { const button=event.target.closest("button");if(!button)return;try{const id=button.dataset.detailEquip||button.dataset.detailLock||button.dataset.detailEnhance||button.dataset.detailDismantle;if(button.dataset.detailEquip){const item=state.game.equipmentBag.find(x=>x.id===id),equipped=item&&state.game.equipped[item.slot]===id;await gameCommand(equipped?"/api/v1/game/equipment/unequip":"/api/v1/game/equipment/equip",equipped?"equipment_unequip":"equipment_equip",equipped?{slot:item.slot}:{equipment_id:id});}else if(button.dataset.detailLock)await gameCommand("/api/v1/game/equipment/lock","equipment_lock",{equipment_id:id});else if(button.dataset.detailEnhance)await gameCommand("/api/v1/game/equipment/enhance","equipment_enhance",{equipment_id:id});else if(button.dataset.detailDismantle)await gameCommand("/api/v1/game/equipment/dismantle","equipment_dismantle",{equipment_id:id});const current=state.game.equipmentBag.find(x=>x.id===id);if(current)showEquipmentDetail(current);else $("equipment-detail").innerHTML="<p>装备已移除</p>";}catch(error){setError("inventory-error",errorText(error));} }
async function handleSkillClick(event) { const button=event.target.closest("[data-skill]");if(!button)return;try{const id=Number(button.dataset.skill),unlocked=button.dataset.unlocked==="true";if(unlocked){const slots=state.game.skillSlots.includes(id)?state.game.skillSlots.filter(x=>x!==id):[...state.game.skillSlots,id];await gameCommand("/api/v1/game/skill/slot","skill_slot",{skill_id:id,slots});}else await gameCommand("/api/v1/game/skill/unlock","skill_unlock",{skill_id:id});}catch(error){setError("skill-error",errorText(error));} }
async function submitAuction(event) {event.preventDefault();setError("auction-error");try{if(!$("auction-item-id").value)throw new Error("没有可上架物品");await api("/api/v1/auction/list",{method:"POST",body:JSON.stringify({rules_version:RULES_VERSION,request_id:requestId("auction"),item_kind:$("auction-kind").value,item_id:$("auction-item-id").value,item_count:Number($("auction-count").value),buyout_price:Number($("auction-price").value),duration_hours:Number($("auction-duration").value)})});$("auction-price").value="";await loadGameState();await refreshAuction();}catch(error){setError("auction-error",errorText(error));}}
async function manageAuction(event) { const buy=event.target.closest("[data-buy-auction]"),cancel=event.target.closest("[data-cancel-auction]"),claim=event.target.closest("[data-claim-auction]"); try { if (buy) { await api("/api/v1/auction/buy", { method:"POST", body:JSON.stringify({ rules_version:RULES_VERSION, request_id:requestId("buy"), listing_id:buy.dataset.buyAuction }) }); } else if (cancel || claim) { await api(cancel?"/api/v1/auction/cancel":"/api/v1/auction/claim", { method:"POST", body:JSON.stringify({ listing_id:(cancel||claim).dataset[cancel?"cancelAuction":"claimAuction"] }) }); } else return; await loadGameState(); await refreshAuction(); } catch(error) { setError("auction-error",errorText(error)); } }
function openOverlay(id) { $all(".overlay").forEach(node=>node.hidden=true);show(id);if(id==="auction-panel")refreshAuction();if(id==="inventory-panel"&&state.game)renderInventory(state.game); }
function closeOverlays() { $all(".overlay").forEach(node=>node.hidden=true); }
function battleUnit(unit, side, index) { const root=document.createElement("div");root.className=`battle-unit ${side}-unit`;root.dataset.unitId=unit.id;const asset=side==="enemy"?(unit.isBoss?`./assets/battle/boss/${encodeURIComponent(unit.asset||unit.name+".png")}`:`./assets/battle/monsters/${unit.asset||"char_0001.png"}`):"./assets/battle-hero.png";root.innerHTML=`<img src="${asset}" alt=""><strong>${unit.displayName||unit.name||"敌人"}</strong><div class="unit-hp"><i></i><span>${unit.currentHp} / ${unit.maxHp}</span></div><div class="status-icons"></div>`;root.style.setProperty("--unit-index",index);return root; }
function playBattle(event) { if(!event.events?.length)return;state.battle={event,events:event.events,index:0,units:event.encounter?.units||[],playerHp:event.playerStartHp||state.game.maxHp,playerMaxHp:event.playerMaxHp||state.game.maxHp,enemyHp:new Map((event.encounter?.units||[]).map(u=>[u.id,u.currentHp]))};show("battle-panel");$("battle-result").hidden=true;$("battle-title").textContent=event.battleKind==="boss"?"BOSS 战":event.battleKind==="elite"?"精英来袭":"遭遇战";$("battle-subtitle").textContent=event.encounter?.templateName||"朱樱山道";$("battle-weather").textContent=`天气 · ${event.encounter?.weather||"晴朗"}`;const enemies=$("battle-enemies");enemies.replaceChildren();state.battle.units.forEach((unit,index)=>enemies.append(battleUnit(unit,"enemy",index)));const player=$("battle-player");player.classList.remove("hit");updateUnitBar(player,state.battle.playerHp,state.battle.playerMaxHp);$("combat-log").replaceChildren();playNextBattleEvent(); }
function updateUnitBar(root,current,max) { const bar=root.querySelector(".unit-hp i"),label=root.querySelector(".unit-hp span");if(bar)bar.style.width=`${Math.max(0,Math.min(100,current/max*100))}%`;if(label)label.textContent=`${Math.max(0,Math.floor(current))} / ${Math.floor(max)}`; }
function playNextBattleEvent() { const battle=state.battle;if(!battle)return;if(battle.index>=battle.events.length){finishBattle();return;}const event=battle.events[battle.index++];const target=event.target==="player"?$("battle-player"):$("battle-enemies").querySelector(`[data-unit-id="${event.targetId}"]`);if(event.type==="cast"){$("battle-callout").textContent=`${event.skillIcon||"⚔"} ${event.skillName||"普通攻击"}`;addCombatLog(`勇者释放 ${event.skillName||"普通攻击"}`);}if(event.type==="damage"&&target){const current=event.remainingHp??(event.target==="player"?battle.playerHp:event.maxHp);if(event.target==="player")battle.playerHp=current;else battle.enemyHp.set(event.targetId,current);updateUnitBar(target,current,event.maxHp||battle.playerMax);target.classList.remove("hit");void target.offsetWidth;target.classList.add("hit");floatDamage(target,event.value,event.critical);addCombatLog(`${event.sourceName||"勇者"} 对 ${event.targetName||"目标"} 造成 ${event.value}${event.critical?" 暴击":""}`);}state.battleTimer=window.setTimeout(playNextBattleEvent,Math.max(180,500/state.battleSpeed)); }
function addCombatLog(text) { const line=document.createElement("p");line.textContent=text;$("combat-log").append(line);const log=$("combat-log");while(log.children.length>5)log.firstElementChild.remove(); }
function floatDamage(target,value,critical) { const node=document.createElement("b");node.className=`float-damage${critical?" critical":""}`;node.textContent=`-${value}`;target.append(node);window.setTimeout(()=>node.remove(),900); }
function finishBattle() { const battle=state.battle;if(!battle)return;const event=battle.event;$("result-title").textContent=event.won?"战斗胜利":"战斗失败";const reward=event.rewards||{};$("result-body").textContent=event.won?`用时 ${event.rounds||0} 回合\n金币 +${reward.gold||0} · 经验 +${reward.experience||0}${reward.equipment?`\n获得：${reward.equipment.name}`:""}`:(event.message||"勇者倒下了");$("battle-result").hidden=false;}
async function logout(){try{if(state.token)await api("/api/v1/auth/logout",{method:"POST"});}catch{}clearSession();}
function clearSession(){if(state.socket)state.socket.close();window.clearTimeout(state.reconnectTimer);window.clearInterval(state.heartbeat);window.clearInterval(state.autoTimer);window.clearTimeout(state.battleTimer);state.autoTimer=null;state.token=null;state.account=null;state.character=null;state.game=null;sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(ACCOUNT_KEY);showLogin();}
$("auth-switch").addEventListener("click",()=>setAuthMode(!state.registerMode));$("auth-form").addEventListener("submit",async event=>{event.preventDefault();setError("auth-error");const button=$("auth-submit");button.disabled=true;try{if(state.registerMode)await register();else await login();}catch(error){setError("auth-error",errorText(error));}finally{button.disabled=false;}});$("character-form").addEventListener("submit",createCharacter);$("chat-form").addEventListener("submit",sendChat);$("logout-button").addEventListener("click",logout);$("roll-button").addEventListener("click",roll);$("auto-roll").addEventListener("change",event=>setAutoRoll(event.target.checked));$("equipment-list").addEventListener("click",handleInventoryClick);$("inventory-list").addEventListener("click",handleInventoryClick);$("equipment-detail").addEventListener("click",handleDetailAction);$("skill-list").addEventListener("click",handleSkillClick);$("auction-form").addEventListener("submit",submitAuction);$("auction-kind").addEventListener("change",renderAuctionChoices);$("auction-refresh").addEventListener("click",refreshAuction);$("auction-list").addEventListener("click",manageAuction);$("auction-mine-list").addEventListener("click",manageAuction);$("inventory-expand").addEventListener("click",async()=>{try{await gameCommand("/api/v1/game/inventory/expand","inventory_expand");}catch(error){setError("inventory-error",errorText(error));}});$("equipment-expand").addEventListener("click",async()=>{try{await gameCommand("/api/v1/game/equipment/expand","equipment_expand");}catch(error){setError("inventory-error",errorText(error));}});$("battle-skip").addEventListener("click",()=>{if(state.battle){window.clearTimeout(state.battleTimer);state.battle.index=state.battle.events.length;playNextBattleEvent();}});$("battle-speed").addEventListener("click",()=>{state.battleSpeed=state.battleSpeed===1?2:state.battleSpeed===2?.75:1;$("battle-speed").textContent=`×${state.battleSpeed}`;});$("battle-confirm").addEventListener("click",()=>{hide("battle-panel");state.battle=null;});$all("[data-open]").forEach(button=>button.addEventListener("click",()=>openOverlay(button.dataset.open)));$all("[data-close]").forEach(button=>button.addEventListener("click",closeOverlays));$all("[data-bag-tab]").forEach(button=>button.addEventListener("click",()=>{$all("[data-bag-tab]").forEach(x=>x.classList.toggle("active",x===button));$("equipment-list").hidden=button.dataset.bagTab!=="equipment";$("inventory-list").hidden=button.dataset.bagTab!=="items";$("gem-list").hidden=button.dataset.bagTab!=="gems";}));
async function restoreSession(){if(!state.token)return;try{const result=await api("/api/v1/characters/me");state.character=result.character;if(state.character)showLoggedIn();else showCharacterCreation();}catch{clearSession();}}
setAuthMode(false);restoreSession();
